### ISSUE TITLE
Suggestion: json

### ISSUE THREAD

**Issue by brianoflondon** [ausbitbank/hive.ausbit.dev#1]
I don't know if any of the other interfaces do this, but could you make a new api endpoint that gave a transaction as JSON?

```https://hive.ausbit.dev/tx/f5b7052ca8b99e6642ec2794785661d7cde29ca3```

Something like:

```https://hive.ausbit.dev/json/tx/f5b7052ca8b99e6642ec2794785661d7cde29ca3/json```

Do tell me if anything like this exists.

**Comment by ausbitbank** [comment]
I have an older api that can be used for this eg: https://hive.ausbit.dev/json/tx/f5b7052ca8b99e6642ec2794785661d7cde29ca3
You can find more usage info/other endpoints here https://api.ausbit.dev/
